baseURL = 'https://katzkawai.org/nikki01/'
languageCode = 'ja-JP'
title = 'わたしのサイト'
theme = "ananke"
canonifyurls = true
publishDir = "docs"
SectionPagesMenu = "main"
resourceDir = "../resources"
Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-blue"
  recent_posts_number = 4

[[params.ananke_socials]]
name = "twitter"
url = "https://twitter.com/GoHugoIO"
